### ISSUE TITLE
Assets not loading

### ISSUE THREAD

**Issue by rwlove** [aceberg/ExerciseDiary#5]
I'm running your container in a Kubernetes cluster and none of the assets are loading.

```
            image:
              repository: aceberg/exercisediary
              tag: 0.1.1@sha256:5d45dff96fdc176ed617cad3d418ac15f722e73568036153bd2c44022fd8face

            env:
              TZ: ${TIMEZONE}         # required, default: ""
              HOST: "0.0.0.0"         # optional, default: 0.0.0.0
              PORT: "8851"            # optional, default: 8851
              THEME: "Darkly"         # optional, default: grass
              COLOR: "dark"           # optional, default: light
```

```
➜  ~ kubectl -n home logs exercisediary-0 -f
2023/12/29 15:52:13 INFO: starting web gui with config /data/ExerciseDiary/config.yaml
2023/12/29 15:52:13 =================================== 
2023/12/29 15:52:13 Web GUI at http://0.0.0.0:8851
2023/12/29 15:52:13 =================================== 
[GIN] 2023/12/29 - 15:53:03 | 200 |    5.941164ms |     192.168.1.1 | GET      "/"
[GIN] 2023/12/29 - 15:53:03 | 200 |     606.845µs |     192.168.1.1 | GET      "/fs/public/css/index.css"
[GIN] 2023/12/29 - 15:53:03 | 200 |      25.474µs |     192.168.1.1 | GET      "/fs/public/js/weight.js"
[GIN] 2023/12/29 - 15:53:03 | 200 |     397.578µs |     192.168.1.1 | GET      "/fs/public/js/heatmap.js"
[GIN] 2023/12/29 - 15:53:03 | 200 |     350.689µs |     192.168.1.1 | GET      "/fs/public/js/index.js"
[GIN] 2023/12/29 - 15:53:04 | 200 |     180.224µs |     192.168.1.1 | GET      "/fs/public/favicon.png"
[GIN] 2023/12/29 - 15:53:04 | 200 |     127.538µs |     192.168.1.1 | GET      "/fs/public/favicon.png"
[GIN] 2023/12/29 - 15:53:10 | 200 |    5.448818ms |     192.168.1.1 | GET      "/"
[GIN] 2023/12/29 - 15:53:10 | 200 |       44.84µs |     192.168.1.1 | GET      "/fs/public/js/heatmap.js"
[GIN] 2023/12/29 - 15:53:10 | 200 |      66.153µs |     192.168.1.1 | GET      "/fs/public/css/index.css"
[GIN] 2023/12/29 - 15:53:10 | 200 |      82.861µs |     192.168.1.1 | GET      "/fs/public/js/index.js"
[GIN] 2023/12/29 - 15:53:10 | 200 |        33.1µs |     192.168.1.1 | GET      "/fs/public/js/weight.js"
[GIN] 2023/12/29 - 15:53:10 | 200 |     160.787µs |     192.168.1.1 | GET      "/fs/public/favicon.png"
[GIN] 2023/12/29 - 15:53:11 | 200 |     116.154µs |     192.168.1.1 | GET      "/fs/public/favicon.png"
[GIN] 2023/12/29 - 16:00:32 | 200 |    6.169077ms |     192.168.1.1 | GET      "/"
...
```

![image](https://github.com/aceberg/ExerciseDiary/assets/9398728/cb685566-060d-44ea-ab7b-07e223067ce8)
